### ISSUE TITLE
Minimum Viable Schedule Editor checklist

### ISSUE THREAD

**Issue by rixx** [pretalx/schedule-editor#1]
- [x] Display current schedule
- [x] Schedule and undschedule talks correctly
- [ ] Push changes to pretalx
- [ ] Show warnings
- [ ] Change details in editor
- [ ] Expand timesteps on click
- [ ] Scroll while dragging talks
- [ ] Handle overlapping sessions

Nice to haves:

- [ ] Schedule release overlay
- [ ] Warnings summary?
- [ ] Find talks (by title, speaker)
- [ ] Filter by track/session type
- [ ] Show speaker availabilities while dragging

Really great to have:

- [ ] Show changes to current schedule
- [ ] multi select talks
- [ ] Show distances to other talks, maybe even snap to equal breaks?
